/* UI for explicitly conditional screening; never writes telemetry or claims field detection. */
(function(){
'use strict';
const S=window.RoadsideSiting,C=window.WildfireCore,P=window.WILDFIRE_PLAN,A=window.WildfireApp,$=id=>document.getElementById(id);
if(!S||!C||!P||!A){return;}
const state={...S.defaults,source:{...P.target},availability:'all',showGrid:true};let evaluation=null,last=null,comparison=null;
const fmt=(n,d=1)=>Number.isFinite(n)?n.toFixed(d):'—';const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const compass=d=>['เหนือ','ตะวันออกเฉียงเหนือ','ตะวันออก','ตะวันออกเฉียงใต้','ใต้','ตะวันตกเฉียงใต้','ตะวันตก','ตะวันตกเฉียงเหนือ'][Math.round(d/45)%8];
const active=()=>P.stations.map(s=>({...s,enabled:state.availability==='all'||state.availability==='east'&&s.side==='E'||state.availability==='west'&&s.side==='W'||state.availability==='north'&&s.side==='N'}));
function label(r){return r.status==='CALM_UNKNOWN'?'ลมสงบ · ประเมินการพัดพาไม่ได้':r.status==='NO_ACTIVE_STATIONS'?'ไม่มีสถานีในฉาก · ไม่ใช่ไม่มีไฟ':r.status==='BEYOND_HORIZON'?'คำนวณได้ช้ากว่ากรอบ 60 นาที':r.status==='NO_INTERCEPTION'?'ไม่มีจุดเข้าแนวควันสมมตินี้':fmt(r.first.minutes)+' นาที';}
function compute(){evaluation=S.evaluate(active(),P.target,state);last=S.screen(active(),state.source,state);const old=window.WILDFIRE_LEGACY_PLAN;comparison=old?S.evaluate(old.stations.map(s=>({...s,enabled:state.availability==='all'||state.availability==='east'&&s.side==='E'||state.availability==='west'&&s.side==='W'||state.availability==='north'&&s.side==='N'})),P.target,state):null;render();A.requestMap();}
function render(){
 $('screen-wind-label').textContent=state.windToDeg+'° · '+compass(state.windToDeg);$('screen-speed-label').textContent=fmt(state.windSpeedMps)+' m/s';$('screen-angle-label').textContent='±'+state.halfAngleDeg+'°';
 const first=last.first,second=last.second,nearest=last.rows.filter(r=>r.status!=='EXCLUDED').sort((a,b)=>a.distanceM-b.distanceM)[0],legacy=S.legacyFirst(active(),state.source,state);
 $('screen-source-summary').innerHTML='<article><span>จุดเริ่มฉาก</span><b>'+fmt(state.source.lat,6)+', '+fmt(state.source.lon,6)+'</b><small>ดับเบิลคลิกในวง 2 กม. เพื่อเปลี่ยนจุด</small></article><article><span>เดินทางถึงจุดแรก + เวลาอุปกรณ์สมมติ</span><b>'+esc(label(last))+'</b><small>'+(first?esc(first.label)+' · เดินทาง '+fmt(first.travelMin)+' + อุปกรณ์ '+fmt(first.delayMin)+' นาที':'ไม่แปลงผลนี้เป็นพื้นที่ปลอดภัย')+'</small></article><article><span>จุดที่สองเข้าแนวควัน</span><b>'+(second?esc(second.label)+' · '+fmt(second.minutes)+' นาที':'ยังไม่มีจุดที่สองในฉาก')+'</b><small>ใช้ประกอบหลักฐาน ไม่รอ 2 จุดก่อนแจ้งให้ตรวจสอบ</small></article><article><span>ทดสอบเกณฑ์ PM + CO สูตรเดิม</span><b>'+(legacy?fmt(legacy.conditionalAlertMin)+' นาที*':'ไม่ผ่านเกณฑ์ภายใน 60 นาที*')+'</b><small>* สังเคราะห์ ไม่ใช่ความไวจริง · จุดใกล้สุด '+(nearest?fmt(nearest.distanceM,0)+' ม.':'—')+'</small></article>';
 const v=evaluation.allDirections,old=comparison&&comparison.allDirections;
 const row=(title,x)=>'<tr><td>'+title+'</td><td>'+x.withinGoal+' / '+x.total+'</td><td>'+fmt(100*x.withinGoal/x.total)+'%</td><td>'+x.noInterception+'</td><td>'+x.beyondHorizon+'</td><td>'+x.unknown+'</td></tr>';
 $('analysis-results').innerHTML='<div class="analysis-heading"><div><p class="eyebrow">SCENARIO TEST · NOT DETECTION PROBABILITY</p><h2>ทดสอบครบ '+evaluation.sourceCount+' จุดเริ่ม × 16 ทิศลม</h2><p>สัดส่วนฉากทางเรขาคณิตที่เข้าแนวควันและทัน '+state.goalMin+' นาที ไม่ใช่เปอร์เซ็นต์พื้นที่ตรวจไฟได้จริง</p></div><span class="neutral-pill">ยังไม่มีผลตรวจภาคสนาม</span></div><div class="table-scroll"><table><thead><tr><th>แผน</th><th>ทันเป้าหมาย / ทุกฉาก</th><th>สัดส่วนฉาก</th><th>ไม่เข้าแนวควัน</th><th>เกิน 60 นาที</th><th>ไม่ทราบ / ไม่มีข้อมูล</th></tr></thead><tbody>'+row('10 จุดรวม N1 — แผนปัจจุบัน',v)+(old?row('8 จุดไกล — แบบก่อนหน้า',old):'')+'</tbody></table></div><p class="screen-fine">ทั้งสองแผนใช้จุดเริ่มและสมมติฐานเดียวกัน นับฉากที่ไม่เข้าแนวและประเมินไม่ได้ด้วยทุกครั้ง ไม่คัดทิ้งเพื่อทำให้ผลดูดี แผนเก่ายังตรวจได้ที่หน้า <a href="./v1.html">รุ่น 8 จุด</a></p><div class="wind-results">'+evaluation.directions.map(r=>'<button type="button" data-screen-bearing="'+r.windToDeg+'" class="wind-result '+(Math.abs(r.windToDeg-state.windToDeg)<1?'selected':'')+'"><span>ไป '+r.windToDeg+'° · '+compass(r.windToDeg)+'</span><b>'+r.withinGoal+' / '+r.total+'</b><i style="--fraction:'+100*r.withinGoal/r.total+'%"></i></button>').join('')+'</div><div class="analysis-warning"><b>ข้อสรุปสำหรับใช้งานจริง</b><span>แนวริมถนนช่วยเรื่องแผงโซลาร์และการบำรุงรักษา แต่ลมที่พัดออกนอกแนว ช่องว่างระหว่างสถานี และควันลอยเหนือช่องรับอากาศยังทำให้พลาดได้ การเพิ่มลมทุกจุดช่วยบอกสภาพที่จุดติดตั้ง ไม่ใช่พิสูจน์ลมทั้งภูเขา</span></div>';
}
const ns='http://www.w3.org/2000/svg';function el(tag,attrs,parent,text){const e=document.createElementNS(ns,tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);if(text!==undefined)e.textContent=text;parent.append(e);return e;}
function path(points){return points.map((p,i)=>{const [x,y]=A.project(p);return(i?'L':'M')+x.toFixed(2)+' '+y.toFixed(2);}).join(' ');}
function overlay(){
 const svg=$('map-svg');if(!svg||!A.getState().hasTerrain)return;svg.querySelector('#study-area-layer')?.remove();const g=document.createElementNS(ns,'g');g.id='study-area-layer';g.setAttribute('pointer-events','none');svg.insertBefore(g,svg.firstChild);
 el('path',{d:path(S.circle(P.target,2000))+'Z',fill:'#eeeecc','fill-opacity':'.04',stroke:'#5069a8','stroke-width':'2','stroke-dasharray':'8 5'},g);
 const [lx,ly]=A.project(C.offset(P.target,0,2000));el('text',{x:lx,y:ly+16,'text-anchor':'middle','font-size':'11',fill:'#344882','paint-order':'stroke',stroke:'#fff','stroke-width':'3'},g,'พื้นที่ศึกษา 2 กม. · ไม่ใช่รัศมีรับประกัน');
 if(A.getState().view!=='analysis'||!evaluation)return;
 if(state.showGrid)for(const cell of evaluation.cells){const r=cell.result,[x,y]=A.project(cell.source);const color=r.status==='INTERCEPTED'?(r.first.minutes<=state.goalMin?'#278462':'#d99936'):['NO_INTERCEPTION','BEYOND_HORIZON'].includes(r.status)?'#885785':'#8a9191';el('circle',{cx:x,cy:y,r:4.2,fill:color,'fill-opacity':'.60'},g);}
 const [x,y]=A.project(state.source);el('circle',{cx:x,cy:y,r:9,fill:'#da4c37',stroke:'#fff','stroke-width':2},g);
 if(state.windSpeedMps>0){const angle=state.windToDeg*Math.PI/180,length=2500,edge=state.captureWidthM+length*Math.tan(state.halfAngleDeg*Math.PI/180);const tip=C.offset(state.source,Math.sin(angle)*length,Math.cos(angle)*length);const a=C.offset(tip,Math.cos(angle)*edge,-Math.sin(angle)*edge),b=C.offset(tip,-Math.cos(angle)*edge,Math.sin(angle)*edge);el('path',{d:path([state.source,a,b])+'Z',fill:'#dbaa57','fill-opacity':'.12',stroke:'#bb8a3b','stroke-width':1,'stroke-dasharray':'4 5'},g);}
 if(last.first){const s=P.stations.find(s=>s.id===last.first.id);el('path',{d:path([state.source,s]),stroke:'#c57035','stroke-width':2,'stroke-dasharray':'3 3'},g);}
 $('map-caption').innerHTML='<b>จุดสี = จุดเริ่มควันที่ใช้ทดสอบ ไม่ใช่เซนเซอร์</b><span>ลมไป '+state.windToDeg+'° · '+fmt(state.windSpeedMps)+' m/s · ดับเบิลคลิกเพื่อเลือกจุดเริ่ม</span>';
}
window.addEventListener('wildfire:map-render',overlay);
for(const[id,key]of [['screen-wind','windToDeg'],['screen-speed','windSpeedMps'],['screen-angle','halfAngleDeg'],['screen-goal','goalMin']])$(id).addEventListener('input',()=>{state[key]=Number($(id).value);compute();});
$('screen-grid').onchange=()=>{state.showGrid=$('screen-grid').checked;A.requestMap();};
$('screen-availability').onchange=()=>{state.availability=$('screen-availability').value;compute();};
$('screen-source').onchange=()=>{const choice=$('screen-source').value;if(choice==='center')state.source={...P.target};else if(choice==='north'||choice==='south')state.source=C.offset(P.target,0,choice==='north'?1500:-1500);else if(choice==='near')state.source=C.offset(P.stations.find(s=>s.screenLabel==='E3'),-100,0);compute();};
$('map').addEventListener('dblclick',event=>{if(A.getState().view!=='analysis'||event.target.closest('button,select,.station-marker'))return;const r=$('map').getBoundingClientRect(),p=A.unproject(event.clientX-r.left,event.clientY-r.top);if(Math.hypot(...C.delta(P.target,p))>2000){$('screen-source-summary').setAttribute('aria-label','โปรดเลือกจุดภายในวง 2 กม.');return;}state.source=p;$('screen-source').value='custom';compute();});
$('analysis-results').addEventListener('click',event=>{const b=event.target.closest('[data-screen-bearing]');if(!b)return;state.windToDeg=Number(b.dataset.screenBearing);$('screen-wind').value=state.windToDeg;compute();});
$('screen-export').onclick=()=>{const report={schemaVersion:1,model:S.MODEL,planVersion:P.version,sourceHash:P.sourceSha256,studyRadiusM:2000,areaKm2:P.studyAreaKm2,assumptions:S.settings(state),availability:state.availability,selectedSource:last,summary:evaluation.allDirections,directions:evaluation.directions,cells:evaluation.cells,comparisonV1:comparison?comparison.allDirections:null,fieldDetectionProbability:null,fieldLatencyVerified:false};const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='wildfire-2km-conditional-screening.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
window.WildfireScreening=Object.freeze({getState:()=>({source:{...state.source},settings:S.settings(state),availability:state.availability,summary:evaluation?.allDirections,result:last})});
compute();
})();
