/* Deterministic transport screening, NOT a calibrated smoke/fire detection model. */
(function(root){
'use strict';
const C=typeof module!=='undefined'&&module.exports?require('./core.js'):root.WildfireCore;
const MODEL='CONSTANT_WIND_GEOMETRIC_INTERCEPTION_NOT_DETECTION';
const defaults=Object.freeze({windToDeg:90,windSpeedMps:2,halfAngleDeg:20,captureWidthM:25,sampleSec:30,persistenceSec:60,uplinkSec:30,horizonMin:60,goalMin:10});
const finite=v=>typeof v==='number'&&Number.isFinite(v);
function point(p){if(!p||!finite(p.lat)||!finite(p.lon)||Math.abs(p.lat)>85||Math.abs(p.lon)>180)throw Error('Invalid WGS84 coordinate');}
function settings(input={}){const o={...defaults,...input};for(const k of Object.keys(defaults))if(!finite(o[k]))throw Error('Invalid '+k);if(o.windSpeedMps<0||o.windSpeedMps>50||o.halfAngleDeg<0||o.halfAngleDeg>60||o.captureWidthM<0||o.captureWidthM>200||o.sampleSec<0||o.persistenceSec<0||o.uplinkSec<0||o.horizonMin<=0||o.goalMin<=0)throw Error('Invalid screening settings');o.windToDeg=((o.windToDeg%360)+360)%360;return o;}
function circle(center,radius=2000,count=120){point(center);if(!finite(radius)||radius<=0)throw Error('Invalid radius');return Array.from({length:count+1},(_,i)=>C.offset(center,Math.sin(i/count*2*Math.PI)*radius,Math.cos(i/count*2*Math.PI)*radius));}
function sampleSources(center,radius=2000,spacing=250){point(center);if(!finite(radius)||radius<=0||radius>10000||!finite(spacing)||spacing<50)throw Error('Invalid sampling domain');const out=[];for(let y=-Math.floor(radius/spacing)*spacing;y<=radius;y+=spacing)for(let x=-Math.floor(radius/spacing)*spacing;x<=radius;x+=spacing)if(x*x+y*y<=radius*radius+1e-8)out.push({...C.offset(center,x,y),eastM:x,northM:y});return out;}
function screen(stations,source,input={}){
 point(source);const o=settings(input),angle=o.windToDeg*Math.PI/180,delay=(o.sampleSec+o.persistenceSec+o.uplinkSec)/60;
 const rows=stations.map(s=>{point(s);const [dx,dy]=C.delta(source,s),alongM=dx*Math.sin(angle)+dy*Math.cos(angle),crossM=Math.abs(dx*Math.cos(angle)-dy*Math.sin(angle));const base={id:s.id,label:s.screenLabel||s.id,distanceM:Math.hypot(dx,dy),alongM,crossM,minutes:null};
 if(s.enabled===false)return {...base,status:'EXCLUDED'};
 if(o.windSpeedMps===0)return {...base,status:'CALM_UNKNOWN'};
 const widthM=o.captureWidthM+Math.max(0,alongM)*Math.tan(o.halfAngleDeg*Math.PI/180);
 if(alongM < -1e-7 || crossM>widthM+1e-7)return {...base,status:'NO_INTERCEPTION',widthM};
 const travelMin=Math.max(0,alongM)/o.windSpeedMps/60,minutes=travelMin+delay;
 return {...base,widthM,travelMin,delayMin:delay,minutes,status:minutes<=o.horizonMin?'INTERCEPTED':'BEYOND_HORIZON'};});
 const hits=rows.filter(r=>r.status==='INTERCEPTED').sort((a,b)=>a.minutes-b.minutes),active=rows.filter(r=>r.status!=='EXCLUDED');
 const status=!active.length?'NO_ACTIVE_STATIONS':o.windSpeedMps===0?'CALM_UNKNOWN':hits.length?'INTERCEPTED':rows.some(r=>r.status==='BEYOND_HORIZON')?'BEYOND_HORIZON':'NO_INTERCEPTION';
 return {model:MODEL,fieldDetectionProbability:null,fieldLatencyVerified:false,source:{...source},settings:o,status,first:hits[0]||null,second:hits[1]||null,rows};
}
function summarize(results,goalMin){const counts={total:results.length,withinGoal:0,intercepted:0,beyondHorizon:0,noInterception:0,unknown:0};let times=[];for(const r of results){if(r.status==='INTERCEPTED'){counts.intercepted++;times.push(r.first.minutes);if(r.first.minutes<=goalMin)counts.withinGoal++;}else if(r.status==='BEYOND_HORIZON')counts.beyondHorizon++;else if(r.status==='NO_INTERCEPTION')counts.noInterception++;else counts.unknown++;}times.sort((a,b)=>a-b);return {...counts,goalMin,scenarioFractionWithinGoal:counts.total?counts.withinGoal/counts.total:null,medianAmongInterceptedMin:times.length?times[Math.floor(times.length/2)]:null,fieldDetectionProbability:null};}
function evaluate(stations,center,input={},spacing=250){const o=settings(input),sources=sampleSources(center,2000,spacing);const cells=sources.map(source=>({source,result:screen(stations,source,o)}));const directions=Array.from({length:16},(_,i)=>{const windToDeg=i*22.5;return {windToDeg,...summarize(sources.map(s=>screen(stations,s,{...o,windToDeg})),o.goalMin)};});const counts=directions.reduce((out,r)=>{for(const k of ['total','withinGoal','intercepted','beyondHorizon','noInterception','unknown'])out[k]+=r[k];return out;},{total:0,withinGoal:0,intercepted:0,beyondHorizon:0,noInterception:0,unknown:0});return {model:MODEL,settings:o,sourceCount:sources.length,spacingM:spacing,areaKm2:Math.PI*4,cells,directions,current:summarize(cells.map(c=>c.result),o.goalMin),allDirections:{...counts,scenarioFractionWithinGoal:counts.total?counts.withinGoal/counts.total:null,fieldDetectionProbability:null}};}
// Original bdteamditto/fire synthetic kernel; no stronger emissions or longer attenuation.
// Time here is minutes SINCE SMOKE RELEASE, not the legacy page's wall-clock offset.
function legacyReading(station,source,elapsed,windToDeg,windSpeedMps){point(station);point(source);if(!finite(elapsed)||elapsed<0)throw Error('Invalid elapsed minutes');settings({windToDeg,windSpeedMps});const [dx,dy]=C.delta(source,station),theta=windToDeg*Math.PI/180,along=dx*Math.sin(theta)+dy*Math.cos(theta),cross=dx*Math.cos(theta)-dy*Math.sin(theta);const local=Math.exp(-(dx*dx+dy*dy)/(2*85**2));const plume=windSpeedMps>0&&along>=0&&along<=windSpeedMps*elapsed*60?Math.exp(-cross**2/(2*(90+.18*along)**2))*Math.exp(-along/900):0;const signal=Math.max(local,plume)*(1-Math.exp(-elapsed/8));const pm=15+130*signal,co=.15+.85*signal;return {pm,co,baselinePm:15,baselineCo:.15,quality:'VALID',synthetic:true,status:pm-15>25&&co-.15>.2?'SUSPECT':'NO_ANOMALY'};}
function legacyFirst(stations,source,input={}){const o=settings(input);for(let minute=0;minute<=o.horizonMin;minute+=.5){for(const s of stations){if(s.enabled===false)continue;const r=legacyReading(s,source,minute,o.windToDeg,o.windSpeedMps);if(r.status==='SUSPECT'){const totalMin=minute+(o.sampleSec+o.persistenceSec+o.uplinkSec)/60;return {id:s.id,thresholdCrossingMin:minute,conditionalAlertMin:totalMin,model:'LEGACY_SYNTHETIC_KERNEL_NOT_VALIDATED',withinHorizon:totalMin<=o.horizonMin};}}}return null;}
function geojson(plan){return {type:'FeatureCollection',features:plan.stations.map(s=>({type:'Feature',properties:{id:s.id,screen_label:s.screenLabel,kit:s.kit,status:plan.status,coordinate_role:'SCREENSHOT_TO_ROAD_SURVEY_ANCHOR_NOT_FOUNDATION',osm_way_id:s.wayId,highway:s.highway,surface:s.surface,motor_vehicle:s.motorVehicle,access:s.access,permission_status:'NOT_VERIFIED',solar_status:'NOT_SURVEYED',radio_status:'NOT_SURVEYED',screenshot_match_error_m:s.hintDistanceM,screenshot_coordinate_uncertainty_m:150,conditional:s.conditional,panel_wp:plan.kits[s.kit].panelWp,battery_v:plan.kits[s.kit].batteryV,battery_ah:plan.kits[s.kit].batteryAh},geometry:{type:'Point',coordinates:[s.lon,s.lat]}}))};}
const api={MODEL,defaults,settings,circle,sampleSources,screen,summarize,evaluate,legacyReading,legacyFirst,geojson};if(typeof module!=='undefined'&&module.exports)module.exports=api;root.RoadsideSiting=api;
})(typeof window!=='undefined'?window:globalThis);
