/* Experimental workbench; inference payload never contains simulator truth. */
(function(){
'use strict';
const P=window.WILDFIRE_PLAN,C=window.WILDFIRE_CONTEXT,I=window.WildfireInverse,T=window.WildfireTerrainPhysics,K=window.WildfireCalibration,G=window.WildfireSimulator,$=id=>document.getElementById(id),NS='http://www.w3.org/2000/svg';
const f=(n,d=2)=>Number.isFinite(n)?n.toFixed(d):'—';
const names={NO_SIGNAL:'ยังไม่พบสัญญาณตามเกณฑ์',PARTICULATE_ONLY:'มีฝุ่นเพิ่ม',PENDING:'กำลังรอความต่อเนื่อง',SIGNAL_HISTORY:'มีประวัติสัญญาณ',INSUFFICIENT_DATA:'ข้อมูลไม่เพียงพอ',WIND_UNAVAILABLE:'ประวัติลมไม่พอ / ลมสงบ',DIRECTIONAL_ONLY:'ได้เพียงแนวต้นลม',MODEL_MISMATCH:'แบบจำลองไม่สอดคล้อง',EXTERNAL_POSSIBLE:'มีสมมติฐานอยู่นอกวงศึกษา',AMBIGUOUS:'หลายสมมติฐานยังเป็นไปได้',CANDIDATE_AREAS:'พื้นที่ต้นทางที่สอดคล้องกับข้อมูล'};
let tab='wind',spec={windToDeg:75,windSpeedMps:2},fixture=G.generate(P,spec),imported=null,current=null,requestId=0,worker=null,revealed=false,selected='R02',calibration=null;
const node=(tag,attrs,host,text)=>{const e=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,String(v));if(text!==undefined)e.textContent=text;host.append(e);return e;};
function failure(text){$('work-error').textContent=text;$('work-error').hidden=false;}
function download(name,data){const a=document.createElement('a'),u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),2000);}
function getOptions(){return T.options({clearanceM:Number($('clearance-input').value),mixingHeightM:Number($('mixing-input').value),frictionVelocityMps:Number($('friction-input').value),diffusivityM2s:Number($('diffusion-input').value),inletHeightM:Number($('inlet-input').value)});}
class WorkMap extends window.WildfireMapView{
 show(){const result=current?.report,rows=P.stations.map(s=>({id:s.id,status:result?.evidence.find(r=>r.id===s.id)?.status==='SUSPECT'?'SUSPECT':result?.evidence.find(r=>r.id===s.id)?.status==='UNKNOWN'?'UNKNOWN':'NO_ANOMALY'}));this.render({view:'dashboard',scenario:'normal',source:P.target,windToDeg:0,windSpeedMps:0,minute:0,smokeDelayMin:0,selected},{rows},{rows:P.stations.map(s=>({id:s.id,enabled:true}))});}
 draw(){super.draw();if(!this.state||!current||!this.width)return;const overlay=node('g',{'pointer-events':'none'},this.svg);const choice=$('area-choice').value,r=choice==='baseline'?current.baseline:choice==='v2b'?current.report:null;
  for(const cell of r?.cells||[]){const [x,y]=this.project(cell),[x2]=this.project(I.geo(cell,cell.sizeM,0)),size=Math.abs(x2-x);node('rect',{x:x-size/2,y:y-size/2,width:size,height:size,fill:choice==='baseline'?'#805c99':'#16868c',opacity:.23,stroke:choice==='baseline'?'#805c99':'#16868c','stroke-width':.4},overlay);}
  for(const a of current.arrows){const[x,y]=this.project(a),s=Math.hypot(a.u,a.v);if(s<.3)continue;const dx=a.u/s*20,dy=-a.v/s*20;node('path',{d:`M${x-dx/2} ${y-dy/2}l${dx} ${dy}m${-dx*.28+dy*.2} ${-dy*.28-dx*.2}L${x+dx/2} ${y+dy/2}l${-dx*.28-dy*.2} ${-dy*.28+dx*.2}`,stroke:'#246e58','stroke-width':1.4,fill:'none'},overlay);}
  if(revealed&&!imported){for(const p of fixture.truth.sources){const[x,y]=this.project(p);node('circle',{cx:x,cy:y,r:9,fill:'#d95d3c',stroke:'white','stroke-width':2,'data-truth-pin':'yes'},overlay);}}
 }
}
const map=new WorkMap('terrain-map',P,C,id=>{selected=id;render();},point=>{if(imported)return;try{const next=G.generate(P,{...spec,point});spec={...spec,point};fixture=next;run();}catch(e){failure(e.message);}});
function render(){if(!current)return;map.show();const r=current.report,field=current.field;
 $('numerical-summary').replaceChildren();for(const[label,value,note]of[['DEM ในกรอบคำนวณ',f(field.minElevationM,0)+'–'+f(field.maxElevationM,0)+' ม.','ข้อมูลสูงต่ำจริงที่แนบมา ไม่ใช่การรังวัด'],['กริดลม',field.spacingM+' ม.','แก้สมการบน 41 × 41 จุด'],['เวลาในการคำนวณ V2B',f(current.elapsedMs/1000,2)+' วินาที','เวลา CPU ไม่ใช่เวลาตรวจพบไฟ']]){const a=document.createElement('article');for(const[tag,text]of[['span',label],['strong',value],['span',note]]){const e=document.createElement(tag);e.textContent=text;a.append(e);}$('numerical-summary').append(a);}
 $('terrain-results').replaceChildren();for(const[k,label]of[['baseline','V1.1 · เดิม'],['report','V2B · ทดลอง']]){const a=document.createElement('div');a.className='result-card '+(k==='report'?'v2b':'');const title=document.createElement('b');title.textContent=label;const val=document.createElement('strong');val.textContent=current[k].cells.length?f(current[k].areaKm2)+' ตร.กม.':'ยังไม่ระบุพื้นที่';const small=document.createElement('span');small.textContent=names[current[k].status]||current[k].status;a.append(title,val,small);$('terrain-results').append(a);}
 const when=document.createElement('p');when.textContent='ข้อมูล ณ '+new Date(r.asOf).toLocaleTimeString('th-TH',{timeZone:'Asia/Bangkok'})+' น. · หลักฐาน '+r.anomalousStations.length+' สถานี'+(r.assessmentDataStatus==='HISTORICAL_EVIDENCE_DATA_GAP'?' · ใช้หลักฐานย้อนหลัง ข้อมูลล่าสุดบางสถานีขาด':'');$('terrain-results').append(when);
 const v=r.windValidation;$('wind-validation').textContent='RMSE เวกเตอร์จาก '+v.sampleCount+' จุด: V2B '+f(v.terrainVectorRmseMps,3)+' m/s · IDW '+f(v.idwVectorRmseMps,3)+' m/s · ลมสม่ำเสมอ '+f(v.uniformVectorRmseMps,3)+' m/s (ยิ่งน้อยยิ่งใกล้ค่าที่กันออก)';
 const e=r.evidence.find(x=>x.id===selected),s=P.stations.find(x=>x.id===selected);$('station-detail').textContent=s.screenLabel+' · '+s.lat.toFixed(6)+', '+s.lon.toFixed(6)+' · PM2.5 '+f(e?.pm25,1)+' µg/m³ · CO '+f(e?.co,2)+' ppm';
 $('packet-kind').textContent=imported?'ไฟล์นำเข้า · ไม่ใช่ Live / ยังไม่สอบเทียบ':'ข้อมูลสังเคราะห์ · ไม่ใช่ Live';$('reveal-source').disabled=!!imported;$('reveal-source').textContent=revealed?'ซ่อนเฉลย':'เปิดเฉลยฉากสาธิต';
}
function run(){let packet,opts;try{opts=getOptions();if(imported)packet=imported;else{const minute=Number($('time-input').value);if(!$('time-input').value.trim()||minute<5||minute>60)throw Error('SCENE_TIME_5_TO_60');spec={...spec,windToDeg:$('wind-input').value.trim()?Number($('wind-input').value):NaN,windSpeedMps:$('speed-input').value.trim()?Number($('speed-input').value):NaN};fixture=G.generate(P,spec);packet=fixture.packetAt(minute);}I.prepareForPlan(packet,P);}catch(e){failure(e.message);return;}
 const id=++requestId;current=null;revealed=false;map.show();$('terrain-results').textContent='กำลังคำนวณชุดใหม่ ไม่ใช้พื้นที่เก่าตัดสิน';$('numerical-summary').replaceChildren();$('wind-validation').replaceChildren();$('station-detail').replaceChildren();$('work-error').hidden=true;$('busy').textContent='กำลังคำนวณ…';$('export-terrain').disabled=true;
 if(worker)worker.terminate();try{worker=new Worker('./terrain-worker.js');worker.onmessage=({data})=>{if(data.id!==requestId)return;$('busy').textContent='';worker.terminate();worker=null;if(data.error){failure(data.error);return;}current=data;$('export-terrain').disabled=false;render();};worker.onerror=()=>{if(id!==requestId)return;worker.terminate();worker=null;$('busy').textContent='';failure('Worker ทำงานไม่ได้ กรุณาเปิดผ่านเว็บ HTTP/HTTPS ไม่ใช้ผลเก่าแทน');};worker.postMessage({id,packet,terrain:C.terrain,options:opts});}catch(e){$('busy').textContent='';failure(e.message);}
}
$('run-terrain').onclick=run;$('area-choice').onchange=()=>map.show();$('reveal-source').onclick=()=>{if(!current||imported)return;revealed=!revealed;render();};
$('observations-file').onchange=async()=>{const file=$('observations-file').files[0];if(!file)return;try{if(file.size>2*1024*1024)throw Error('OBSERVATIONS_MAX_2MB');const p=JSON.parse(await file.text());I.prepareForPlan(p,P);getOptions();imported=p;for(const id of ['time-input','wind-input','speed-input'])$(id).disabled=true;run();}catch(e){failure('ไม่นำเข้าไฟล์นี้: '+e.message+' · คงชุดข้อมูลเดิม');}};
$('reset-demo').onclick=()=>{imported=null;for(const id of ['time-input','wind-input','speed-input'])$(id).disabled=false;run();};
$('export-terrain').onclick=()=>{if(current)download('wildfire-v2b-comparison.json',{schemaVersion:1,mode:imported?'IMPORTED_UNVERIFIED':'SYNTHETIC_TEST',...current,fieldValidated:false});};
function renderPlume(){try{const o=getOptions(),heat=Number($('heat-input').value),speed=$('plume-speed').value.trim()?Number($('plume-speed').value):NaN,values=[];for(let minute=0;minute<=30;minute++)values.push({minute,...T.plume(minute*60,speed,heat,o)});const svg=$('plume-chart');svg.replaceChildren();$('plume-table').replaceChildren();if(values[0].heightM===null){$('plume-notice').textContent='ลมต่ำกว่า 0.5 m/s · อยู่นอกขอบเขตสูตร ไม่ประมาณเป็นศูนย์';return;}$('work-error').hidden=true;$('plume-notice').textContent='สมมติความร้อน '+f(heat/1e6,1)+' MW · ผลคำนวณไม่ใช่ค่าที่วัดจากไฟจริง';
 const max=Math.max(20,...values.map(v=>v.heightM))*1.15;node('path',{d:'M50 20V260H680',fill:'none',stroke:'#7b8d7b'},svg);for(let k=0;k<=4;k++){const y=260-k*60;node('line',{x1:50,y1:y,x2:680,y2:y,stroke:'#dfe3d5'},svg);node('text',{x:42,y:y+4,'text-anchor':'end','font-size':11,fill:'#51665a'},svg,f(k/4*max,0));}for(const m of [0,5,10,15,20,25,30])node('text',{x:50+m/30*620,y:281,'text-anchor':'middle','font-size':12,fill:'#51665a'},svg,m+' นาที');node('path',{d:values.map((v,i)=>(i?'L':'M')+(50+v.minute/30*620)+' '+(260-v.heightM/max*240)).join(' '),fill:'none',stroke:'#147c81','stroke-width':3,'data-height-curve':'yes'},svg);
 for(const m of [2,5,10,20,30]){const v=values[m],zero=T.plume(m*60,speed,0,o),ratio=v.verticalFactor/zero.verticalFactor;const tr=document.createElement('tr');for(const text of [m+' นาที',f(v.heightM,1)+' ม.',ratio<.00001?'<0.001%':f(ratio*100,3)+'%']){const td=document.createElement('td');td.textContent=text;tr.append(td);}$('plume-table').append(tr);}
 }catch(e){$('plume-chart').replaceChildren();$('plume-table').replaceChildren();$('plume-notice').textContent='พารามิเตอร์ไม่ถูกต้อง ยังไม่มีผลใหม่';failure(e.message);}}
$('update-plume').onclick=renderPlume;
function renderCalibration(r){calibration=r;$('calibration-results').replaceChildren();const h=document.createElement('div');h.className='cal-meta';const b=document.createElement('b');b.textContent=r.sourceKind==='SYNTHETIC_TEST'?'ข้อมูลสังเคราะห์สำหรับทดสอบซอฟต์แวร์ — ไม่ใช่ผลภาคสนาม':'ข้อมูลวัดร่วมที่ผู้ใช้นำเข้า — ยังไม่ตรวจสอบเครื่องอ้างอิง';const p=document.createElement('p');p.textContent='ผล: '+r.status+' · ไม่ใช่ใบรับรอง · ไม่เปิดใช้กับเซนเซอร์จริงอัตโนมัติ';h.append(b,p);$('calibration-results').append(h);
 for(const s of r.stations){const title=document.createElement('h3');title.textContent=s.stationId+' · ฝึก '+s.trainingCount+' แถว / ตรวจ '+s.validationCount+' แถว · '+s.status;$('calibration-results').append(title);const div=document.createElement('div');div.className='table-scroll';const table=document.createElement('table');table.innerHTML='<thead><tr><th>ช่อง</th><th>ค่าปรับแก้จากช่วงฝึก</th><th>RMSE ชุดที่กันไว้ ก่อน → หลัง</th><th>สถานะ</th></tr></thead>';const body=document.createElement('tbody');for(const[k,c]of Object.entries(s.channels)){const row=document.createElement('tr');for(const text of[k,c.coefficients?f(c.coefficients.offset,4)+' + '+f(c.coefficients.gain,4)+' × ค่าดิบ':'ยังประมาณไม่ได้',c.validationRaw?f(c.validationRaw.rmse,4)+' → '+f(c.validationCorrected.rmse,4)+' '+c.unit:'—',c.status]){const td=document.createElement('td');td.textContent=text;row.append(td);}body.append(row);}table.append(body);div.append(table);$('calibration-results').append(div);}
 $('export-calibration').disabled=false;$('calibration-error').hidden=true;
}
$('template-calibration').onclick=()=>download('wildfire-collocation-template.json',K.template());$('demo-calibration').onclick=()=>renderCalibration(K.analyze(K.example()));$('export-calibration').onclick=()=>{if(calibration)download('wildfire-calibration-candidate.json',calibration);};
$('calibration-file').onchange=async()=>{const file=$('calibration-file').files[0];if(!file)return;try{if(file.size>4*1024*1024)throw Error('CALIBRATION_MAX_4MB');const data=JSON.parse(await file.text());const prepared=K.prepare(data);if(prepared.rows.some(r=>!P.stations.some(s=>s.id===r.stationId)))throw Error('STATION_NOT_IN_THIS_PLAN');renderCalibration(K.analyze(data));}catch(e){$('calibration-error').hidden=false;$('calibration-error').textContent='ไม่นำเข้าไฟล์นี้: '+e.message+' · ไม่เปลี่ยนผลชุดก่อนหน้า';}};
function setTab(name){tab=name;for(const v of ['wind','plume','calibration']){$(v+'-view').hidden=v!==tab;document.querySelector('[data-tab="'+v+'"]').setAttribute('aria-selected',String(v===tab));}if(tab==='wind')map.show();if(tab==='plume')renderPlume();}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));
window.WildfireTerrainLab=Object.freeze({getState:()=>JSON.parse(JSON.stringify({tab,requestId,report:current?.report||null,baseline:current?.baseline||null,field:current?.field||null,busy:!!worker,imported:!!imported,calibration,fieldValidated:false}))});
run();
})();
