const test=require('node:test'),assert=require('node:assert/strict'),C=require('../calibration'),clone=x=>JSON.parse(JSON.stringify(x));
test('software example is always visibly synthetic, never live-approved or field-validated',()=>{const r=C.analyze(C.example());assert.equal(r.sourceKind,'SYNTHETIC_TEST');assert.equal(r.fieldValidated,false);assert.equal(r.usableForLive,false);assert.equal(r.stations[0].status,'CANDIDATE_FOR_REVIEW');});
test('chronological train/validation sets have disjoint averages with a guard gap',()=>{const s=C.analyze(C.example()).stations[0];assert.equal(s.trainingCount,83);assert.equal(s.validationCount,36);assert.ok(Date.parse(s.validationFrom)-Date.parse(s.trainingThrough)>60000);});
test('affine regression recovers known arithmetic, not a claim of field accuracy',()=>{const s=C.analyze(C.example()).stations[0];assert.ok(Math.abs(s.channels.pm25.coefficients.gain-.8)<1e-8);assert.ok(Math.abs(s.channels.co.coefficients.offset-.03)<1e-8);assert.ok(s.channels.pm25.validationCorrected.rmse<s.channels.pm25.validationRaw.rmse);});
test('changing validation references does not change trained coefficients',()=>{const a=C.example(),x=C.analyze(a).stations[0],b=clone(a);for(const r of b.rows.slice(84)){r.pm25Reference+=100;r.coReference+=2;}const y=C.analyze(b).stations[0];assert.deepEqual(x.channels.pm25.coefficients,y.channels.pm25.coefficients);assert.deepEqual(x.channels.co.coefficients,y.channels.co.coefficients);assert.equal(y.status,'NOT_READY');});
test('reject misaligned clocks, malformed or timezone-free timestamps and duplicate conflicts',()=>{const p=C.example();p.rows[0].referenceObservedAt='2026-03-15T06:01:00Z';assert.throws(()=>C.prepare(p),/ALIGNMENT/);const q=C.example();q.rows[0].observedAt='2026-03-15 06:00:00';assert.throws(()=>C.prepare(q),/TIMESTAMP/);const x=C.example();x.rows.push({...x.rows[0],coRaw:9});assert.throws(()=>C.prepare(x),/DUPLICATE/);});
test('exact duplicates and timezones normalize without changing calibration',()=>{const p=C.example(),r=C.analyze(p);p.rows[0].observedAt='2026-03-15T13:00:00+07:00';p.rows.push({...p.rows[0]});const a=C.analyze(p);assert.deepEqual(a.stations,r.stations);assert.equal(a.duplicateRows,1);});
test('reject overlapping 60-second averages as independent samples',()=>{const p=C.example(),r={...p.rows[0],observedAt:'2026-03-15T06:00:05Z',referenceObservedAt:'2026-03-15T06:00:05Z'};p.rows.push(r);assert.throws(()=>C.prepare(p),/OVERLAPPING/);});
test('missing readings are excluded, not treated as zeros; no data yields no profile',()=>{const p=C.example();p.rows[0].coRaw=null;assert.equal(C.analyze(p).excludedRows,1);const q=C.example();q.rows=[];assert.equal(C.analyze(q).status,'NO_DATA');const r=C.example();r.rows=r.rows.slice(0,30);assert.equal(C.analyze(r).stations[0].status,'INSUFFICIENT_PAIRED_DATA');});
test('reject incorrect units and missing reference provenance',()=>{const p=C.example();p.units.co='ppb';assert.throws(()=>C.prepare(p),/UNITS/);const q=C.example();q.reference.serial='';assert.throws(()=>C.prepare(q),/METADATA/);const r=C.example();r.reference.id='FILL_REFERENCE_MODEL';assert.throws(()=>C.prepare(r),/METADATA/);});
test('a flat background cannot support a general-range calibration',()=>{const p=C.example();p.rows.forEach(r=>{r.coRaw=.2;r.coReference=.15;});const r=C.analyze(p);assert.equal(r.stations[0].channels.co.status,'INSUFFICIENT_CONCENTRATION_RANGE');assert.equal(r.stations[0].status,'NOT_READY');});
test('validation out of training range does not pass',()=>{const p=C.example();p.rows.slice(84).forEach(r=>{r.pm25Raw=300;r.pm25Reference=245;});assert.equal(C.analyze(p).stations[0].channels.pm25.status,'VALIDATION_EXTRAPOLATION');});
test('field-labelled uploads remain unverified even when affine diagnostics pass',()=>{const p=C.example();p.sourceKind='FIELD_COLLOCATION_UPLOAD';const r=C.analyze(p);assert.equal(r.fieldValidated,false);assert.equal(r.usableForLive,false);assert.ok(r.warnings.includes('USER_REFERENCE_METADATA_NOT_INDEPENDENTLY_VERIFIED'));});
test('malformed metadata, unbounded files, forbidden keys and bad humidity fail explicitly',()=>{assert.throws(()=>C.prepare({...C.example(),fieldValidated:true}),/CONTRACT/);const p=C.example();p.rows[0].relativeHumidityPct=101;assert.throws(()=>C.prepare(p),/HUMIDITY/);const q=C.example();q.rows=Array(20001).fill(q.rows[0]);assert.throws(()=>C.prepare(q),/SIZE/);});

test('duplicate metadata conflicts are rejected independently of row order',()=>{const p=C.example(),a={...p.rows[0]},b={...a};delete b.temperatureC;for(const pair of [[a,b],[b,a]])assert.throws(()=>C.prepare({...p,rows:pair}),/DUPLICATE_CONFLICT/);});
