"""One-shot source migration for the N1 feature branch, not a runtime patch."""
from pathlib import Path
import json, math
changed=[]
def patch(file,pairs):
    p=Path(file);text=p.read_text(encoding='utf-8')
    for old,new in pairs:
        assert old in text,(file,old)
        text=text.replace(old,new)
    p.write_text(text,encoding='utf-8');changed.append(file)
plan=json.loads(Path('data/plan-v2.json').read_text())
assert plan['version']=='roadside-2km-v2' and len(plan['stations'])==9
Path('data/plan-before-north.json').write_text(json.dumps(plan,ensure_ascii=False,indent=2)+'\n')
lat=18+49/60+53.6/3600;lon=98+51/60+38.5/3600;R=6371008.8
x=math.radians(lon-plan['target']['lon'])*R*math.cos(math.radians(plan['target']['lat']));y=math.radians(lat-plan['target']['lat'])*R
plan['version']='roadside-2km-v3-north'
plan['stations'].append({'id':'R10','screenLabel':'N1','label':'N1 · จุดเฝ้าระวังทิศเหนือ','side':'N','kit':'WX','lat':lat,'lon':lon,'elevationM':1134,'wayId':None,'highway':'unknown','surface':'unknown','motorVehicle':'unknown','access':'unknown','osmTags':{},'sampleId':'USER_DMS_N1','hintDistanceM':None,'coordinateRole':'USER_SUPPLIED_COORDINATE_NOT_SURVEYED','coordinateSource':'USER_DMS','sourceDms':'18°49\'53.6"N 98°51\'38.5"E','distanceM':round(math.hypot(x,y),1),'distanceModel':'LOCAL_EQUIRECTANGULAR_MEAN_EARTH','gateway':None,'gatewayCandidates':['R01','R06'],'radioStatus':'NOT_SURVEYED','nearbyRoad':{'wayId':1229003512,'distanceM':28.7,'highway':'track','surface':'unpaved','motorVehicle':'private','source':'data/context.json simplified OSM geometry; NOT a surveyed road match'},'reason':'เพิ่มจุดรับควันและวัดลมด้านเหนือ ตามพิกัดผู้ใช้ โดยไม่ย้ายจุดเดิมหรือขยับหมุดเข้าถนนอัตโนมัติ','fieldNote':'พิกัดจากผู้ใช้โดยตรง ไม่ใช่จุดที่จับเข้ากึ่งกลางถนน · แนวทาง OSM ใกล้สุดประมาณ 29 ม. ระบุ motor_vehicle=private · ต้องตรวจแนวทาง สิทธิ์เข้าถึง แดด ไหล่ทาง และวิทยุ ก่อนเลือก Gateway; ยังไม่ยืนยันลิงก์สื่อสาร','conditional':True})
serialized=json.dumps(plan,ensure_ascii=False,indent=2)+'\n'
Path('data/plan-v2.json').write_text(serialized)
Path('data/plan.js').write_text('/* Canonical 10-station plan. N1 retains the exact user DMS coordinate. */\nwindow.WILDFIRE_PLAN = '+serialized.rstrip()+';\n')
patch('console-model.js',[("['all', 'east', 'west', 'none']","['all', 'east', 'west', 'north', 'none']"),("state.availability === 'west' && station.side === 'W'","state.availability === 'west' && station.side === 'W' || state.availability === 'north' && station.side === 'N'"),("detail: 'สถานีริมทาง 9 จุด · ไม่มีการรับข้อมูลจริง'","detail: 'สถานีริมทาง ' + plan.stations.length + ' จุด · ไม่มีการรับข้อมูลจริง'")])
patch('console.js',[("state.minute = preset === 'offline' ? 20 : 10; recalculate();","state.minute = preset === 'offline' ? 20 : 10; if (preset === 'north') state.selected = 'R10'; recalculate();")])
patch('index.html',[('9 สถานีริมทาง','10 สถานีริมทาง · เพิ่ม N1 ทิศเหนือ'),('ครบ 9 จุด','ครบ 10 จุด'),('<option value="none">ไม่มีสถานีพร้อม</option>','<option value="north">เฉพาะทิศเหนือ N1</option><option value="none">ไม่มีสถานีพร้อม</option>')])
patch('planning.html',[('9 จุด','10 จุด'),('10 จุดตามแนวที่วงไว้','9 จุดตามภาพ + N1 ทิศเหนือ'),('9 หมุด','10 หมุด'),('>9 <small>','>10 <small>'),('>09</span>','>10</span>'),('ตะวันออก 5 · ตะวันตก 4','ตะวันออก 5 · ตะวันตก 4 · เหนือ 1'),('860','940'),('<option value="none">ไม่มีจุดพร้อมใช้งาน</option>','<option value="north">เฉพาะเหนือ N1</option><option value="none">ไม่มีจุดพร้อมใช้งาน</option>'),('<button data-side="W" aria-pressed="false">ตะวันตก</button>','<button data-side="W" aria-pressed="false">ตะวันตก</button><button data-side="N" aria-pressed="false">เหนือ</button>'),('8 ทางเกษตร/ทางดิน + 1 แนวถนน','9 จุดเดิม + N1 พิกัดจากผู้ใช้'),('ช่องว่างด้านเหนือและรอบนอกยังมี','เพิ่ม N1 ด้านเหนือแล้ว แต่ไม่รับประกันการตรวจครบทุกทิศ'),('href="./docs/DESIGN_V2.md"','href="./docs/NORTH_STATION.md"')])
patch('app.js',[("unpaved: 'ไม่ลาดยาง'","unpaved: 'ไม่ลาดยาง', unknown: 'ยังไม่สำรวจ'"),("(s.side === 'E' ? 'ตะวันออก' : 'ตะวันตก')","({ E: 'ตะวันออก', W: 'ตะวันตก', N: 'เหนือ' }[s.side] || 'ยังไม่ระบุ')"),("(s.conditional ? 'ทางดิน · ต้องตรวจสิทธิ์' : 'รอสำรวจหน้างาน')","(s.coordinateSource === 'USER_DMS' ? 'พิกัดผู้ใช้ · รอสำรวจ' : s.conditional ? 'ทางดิน · ต้องตรวจสิทธิ์' : 'รอสำรวจหน้างาน')"),("+ s.gateway +","+ (s.gateway || 'รอทดสอบสัญญาณ') +"),("+ s.wayId +","+ (s.wayId || s.nearbyRoad?.wayId || '') +"),('ตรวจถนนต้นทาง OSM #','ตรวจแนวทางอ้างอิง OSM #'),("const points = window.RoadsideSiting.circle(plan.target, plan.studyRadiusM).map(p => C.world(p.lat, p.lon));","const points = [...window.RoadsideSiting.circle(plan.target, plan.studyRadiusM), ...stations].map(p => C.world(p.lat, p.lon));"),("'wildfire-roadside-9-stations.'","'wildfire-roadside-' + stations.length + '-stations.'"),("toast('ส่งออก 9 หมุดแล้ว","toast('ส่งออก ' + stations.length + ' หมุดแล้ว"),('href="./docs/DESIGN.md"','href="./docs/NORTH_STATION.md"')])
patch('siting-ui.js',[("state.availability==='west'&&s.side==='W'","state.availability==='west'&&s.side==='W'||state.availability==='north'&&s.side==='N'"),('9 จุดตามภาพ — แบบใหม่','10 จุดรวม N1 — แผนปัจจุบัน'),('จุดอับตอนเหนือ','ช่องว่างระหว่างสถานี')])
patch('siting.js',[("coordinate_role:'SCREENSHOT_TO_ROAD_SURVEY_ANCHOR_NOT_FOUNDATION'","coordinate_role:s.coordinateRole||'SCREENSHOT_TO_ROAD_SURVEY_ANCHOR_NOT_FOUNDATION',coordinate_source:s.coordinateSource||'SCREENSHOT_TO_OSM',side:s.side,nearby_osm_way_id:s.nearbyRoad?.wayId||null,nearby_road_distance_m:s.nearbyRoad?.distanceM??null,gateway_id:s.gateway??null,gateway_status:s.gateway?'PROPOSED_NOT_SURVEYED':'UNASSIGNED_PENDING_RF_SURVEY'"),('screenshot_coordinate_uncertainty_m:150',"screenshot_coordinate_uncertainty_m:s.coordinateSource==='USER_DMS'?null:150")])
patch('core.js',[("coordinate_role: 'ROAD_CENTERLINE_SURVEY_ANCHOR_NOT_FOUNDATION'","coordinate_role: s.coordinateRole || 'ROAD_CENTERLINE_SURVEY_ANCHOR_NOT_FOUNDATION'"),("quote(s[k])","quote(s[k] ?? '')"),("quote('ROAD_CENTERLINE_SURVEY_ANCHOR_NOT_FOUNDATION')","quote(s.coordinateRole || 'ROAD_CENTERLINE_SURVEY_ANCHOR_NOT_FOUNDATION')"),("xml('PROPOSED. Road centerline survey anchor, not foundation. Solar, permissions and radio NOT VERIFIED. OSM way ' + s.wayId + '. ' + s.reason)","xml((s.coordinateSource === 'USER_DMS' ? 'PROPOSED. Exact user coordinate, NOT snapped to road; NOT surveyed or approved. ' : 'PROPOSED. Road centerline survey anchor, not foundation. ') + 'Solar, permissions and radio NOT VERIFIED. ' + (s.wayId ? 'OSM way ' + s.wayId + '. ' : 'Road and gateway match NOT VERIFIED. ') + s.reason)")])
patch('tests/siting.test.cjs',[("const P=b.window.WILDFIRE_PLAN,O=P.target;","const Current=b.window.WILDFIRE_PLAN;const P=JSON.parse(fs.readFileSync('data/plan-before-north.json','utf8')),O=P.target;"),("const r=S.evaluate(P.stations,O);","const r=S.evaluate(Current.stations,O);"),("const calm=S.evaluate(P.stations,O,{windSpeedMps:0});","const calm=S.evaluate(Current.stations,O,{windSpeedMps:0});")])
patch('tests/console.test.cjs',[('canonical nine-node','canonical ten-node'),("assert.equal(P.stations.length,9)","assert.equal(P.stations.length,10)"),("'roadside-2km-v2'","'roadside-2km-v3-north'"),("assert.equal(rows[0].firstArrival,null)","assert.equal(rows[0].firstArrival.id,'R10')"),("unknown.length,9)","unknown.length,10)")])
patch('tests/console_browser.py',[('to_have_count(9)','to_have_count(10)'),("['stationCount']==9","['stationCount']==10"),('real nine-node','real ten-node')])
patch('tests/siting_browser.py',[('to_have_count(9)','to_have_count(10)'),('length === 9','length === 10'),("'860'","'940'"),("'9 / 9'","'10 / 10'"),("len(data['features'])==9","len(data['features'])==10"),("text.count('<Placemark>')==9","text.count('<Placemark>')==10"),("len(text.strip().splitlines())==10","len(text.strip().splitlines())==11"),("assert page.evaluate('WildfireScreening.getState().result.status')=='NO_INTERCEPTION'","assert page.evaluate('WildfireScreening.getState().result.first.id')=='R10'"),('Nine nearer','Ten current'),('Nine-coordinate','Ten-coordinate'),('northern miss','northern interception')])
patch('scripts/assess_roadside_v2.cjs',[("stationCount:9","stationCount:p.stations.length,planVersion:p.version")])
patch('scripts/build.cjs',[("'docs/OPERATOR_EXPLAINER.md'","'docs/OPERATOR_EXPLAINER.md','docs/NORTH_STATION.md'"),('nine-station plan','ten-station plan')])
p=Path('README.md');t=p.read_text().replace('9 จุด','10 จุด').replace('ทั้ง 10 จุด E1–E5 / W1–W4','ทั้ง 10 จุด E1–E5 / W1–W4 / N1')
p.write_text(t+'\n## N1 ทิศเหนือ\nเพิ่ม R10 / N1 ตามพิกัดผู้ใช้ 18°49\'53.6"N 98°51\'38.5"E = 18.831555556, 98.860694444 โดยไม่ย้ายเก้าจุดเดิม รายละเอียดและผลทดสอบอยู่ใน [NORTH_STATION.md](docs/NORTH_STATION.md)\n')
print(json.dumps({'changed':changed,'stationCount':10,'north':plan['stations'][-1]},ensure_ascii=False,indent=2))
