const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const C=require('../core.js'),S=require('../siting.js'),I=require('../inverse-engine.js');
const out=path.resolve('site');fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(out,{recursive:true});
const files=['bayes-engine.js','bayes-worker.js','bayes-panel.js','bayes.css','v2a-simulator.js','docs/V2A_BAYESIAN.md','index.html','forward.html','planning.html','v1.html','inverse-engine.js','inverse-worker.js','inverse-simulator.js','inverse-ui.js','inverse.css','console.css','console-model.js','console-map.js','console.js','styles.css','core.js','core-v1.js','app.js','app-v1.js','history.js','history.css','siting.js','siting-ui.js','siting.css','data/context.js','data/context.json','data/plan.js','data/plan-v2.json','data/plan-v1.js','data/plan-v1-compare.js','docs/DESIGN.md','docs/DESIGN_V2.md','docs/LEGACY_REFERENCE.md','docs/OPERATOR_EXPLAINER.md','docs/NORTH_STATION.md','docs/INVERSE_SOURCE.md','docs/REVIEW_FIXES.md'];
for(const file of files){const destination=path.join(out,file);fs.mkdirSync(path.dirname(destination),{recursive:true});fs.copyFileSync(file,destination);}
fs.writeFileSync(path.join(out,'.nojekyll'),'');
const box={window:{}};vm.runInNewContext(fs.readFileSync('data/plan.js','utf8'),box);const plan=box.window.WILDFIRE_PLAN;
fs.writeFileSync(path.join(out,'data/stations.geojson'),JSON.stringify(S.geojson(plan),null,2));fs.writeFileSync(path.join(out,'data/stations.csv'),C.csv(plan));fs.writeFileSync(path.join(out,'data/stations.kml'),C.kml(plan));
fs.writeFileSync(path.join(out,'data/study-area.geojson'),JSON.stringify({type:'Feature',properties:{role:'REQUESTED_STUDY_AREA_NOT_CERTIFIED_DETECTION_COVERAGE',radius_m:2000,area_km2:Math.PI*4},geometry:{type:'Polygon',coordinates:[S.circle(plan.target).map(p=>[p.lon,p.lat])]}}));
if(fs.existsSync('qa/screening-v2.json'))fs.copyFileSync('qa/screening-v2.json',path.join(out,'data/screening-baseline.json'));
if(!fs.existsSync('qa/v2a-benchmark.json'))throw Error('V2A_BENCHMARK_REQUIRED_BEFORE_BUILD');
const benchmark=JSON.parse(fs.readFileSync('qa/v2a-benchmark.json'));if(benchmark.challengerVersion!==require('../bayes-engine.js').VERSION)throw Error('V2A_BENCHMARK_VERSION_MISMATCH');
fs.copyFileSync('qa/v2a-benchmark.json',path.join(out,'data/v2a-benchmark.json'));
const assets={};for(const file of ['bayes-engine.js','bayes-worker.js','bayes-panel.js','bayes.css','v2a-simulator.js','data/v2a-benchmark.json','index.html','inverse-engine.js','inverse-worker.js','inverse-simulator.js','inverse-ui.js','inverse.css'])assets[file]=crypto.createHash('sha256').update(fs.readFileSync(path.join(out,file))).digest('hex');
fs.writeFileSync(path.join(out,'version.json'),JSON.stringify({sourceCommit:process.env.GITHUB_SHA||'local',appVersion:'inverse-source-v2a',challengerVersion:require('../bayes-engine.js').VERSION,defaultAlgorithm:'baseline',modelVersion:I.VERSION,planVersion:plan.version,stationCount:plan.stations.length,primaryViews:['dashboard','principles'],mode:'SYNTHETIC_OR_IMPORTED_OBSERVATIONS_NOT_LIVE',fieldValidated:false,assets,generatedAt:new Date().toISOString()},null,2));
console.log('Built observation-only inverse dashboard and blind lab; all ten stations and previous tools preserved.');
